Posture tables
armosec/armoapi-go pull request #118
Opened 2023-08-03 10:52 UTC by avrahams

2023-08-03 12:28 UTC, Bezbran requested changes

2023-08-03 12:28 UTC, Bezbran commented on postgresmodels/posture.go
> +	ControlsScanResults []ControlScanResult  `gorm:"foreignKey:ReportGUID"`
we shouldn't have such constraints so we can be agnostic to the insertion order.

2023-08-03 12:28 UTC, Bezbran commented on postgresmodels/posture.go
> +	FailedControl   pq.StringArray `gorm:"type:text[]"`
We need to have control to resource relation table (ctrl_id,rsrc_id,status,sub_Status, etc.)

2023-08-03 12:28 UTC, Bezbran commented on postgresmodels/posture.go
> +	Images                   datatypes.JSON `gorm:"type:json"`
report guid, resource id, cont name, image name, image hash

2023-08-09 10:38 UTC, Bezbran commented
/describe

2023-08-09 10:40 UTC, Bezbran commented
/describe

2023-08-09 10:50 UTC, Bezbran commented on postgresmodels/posture.go
> +type FrameworkSummary struct {
comment why we need it, since we can calculate it using the ControlScanResult records

2023-08-09 10:50 UTC, Bezbran commented on postgresmodels/posture.go
> +	HighlightsPaths   datatypes.JSON `gorm:"type:json"` //map controlID to []PosturePaths
maybe a table for:
report,rsrc,ctrl,fixPath,fixKind

2023-08-09 10:50 UTC, Bezbran commented on postgresmodels/posture.go
> +	ImageTag      string
ImageHash

2023-08-09 17:09 UTC, avrahams commented on postgresmodels/posture.go
> +	ImageTag      string
done

2023-08-10 07:29 UTC, avrahams commented on postgresmodels/pagination.go
> +}
we also agreed that the chunks counter should be a dedicated table and not extension to another table

2023-08-10 07:49 UTC, Bezbran approved these changes

2023-08-10 07:49 UTC, Bezbran commented on postgresmodels/pagination.go
> +}
@YiscahLevySilas1 I see the need here - let's do it in the next phase

2023-08-10 08:11 UTC, merged